go_src/vagrant-vmware-utility/driver/base.go
go_src/vagrant-vmware-utility/driver/core.go
go_src/vagrant-vmware-utility/utility/vmware_paths_darwin.go
go_src/vagrant-vmware-utility/utility/vmware_paths_linux.go
go_src/vagrant-vmware-utility/utility/vmware_paths_windows.go

Fusion version 12 on Big Sur started using the Apple native vmnet framework.
However, issues with transiting VPNs is requiring VMware to move back to the
VMware DHCP implementation.
Changes:
- Use Apple networking with Big Sur and Fusion versions 12.0 and 12.1
- Switch back to using VMware networking in Fusion version 12.2+
- All other cases will use VMware networking
- Additionally, handle pre-release "experimental" builds that show a
build number of "e.x.p" with VMware networking
Signed-off-by: Mark Peek <markpeek@vmware.com>

Update MacOS lease file detection

---

go_src/vagrant-vmware-utility/internal/service/port_forwarding.go
lib/vagrant-vmware-desktop/driver/base.rb
lib/vagrant-vmware-desktop/errors.rb
locales/en.yml

Adds support for UDP port forwards in the internal forwarding implementation.
Fixes #11

Add support for UDP forwarding

---

lib/vagrant-vmware-desktop/driver/base.rb
lib/vagrant-vmware-desktop/synced_folder.rb

Removes more special characters from the guest path when
creating the synced folder named used for sharing within
the guest. This prevents encoded characters from being
introduced into the name and breaking the generated link.
Fixes #9

Fix synced folder name with Windows paths

---

go_src/vagrant-vmware-utility/command/service_darwin.go

When handling port forwarding internally, a large number of port forwards
can exhaust the some what limited default max open files setting of 256.
This updates the soft limit to 4096 to prevent reaching the max so easily.
Fixes #15

Increase soft limit for max open files

---

.github/workflows/test.yml
lib/vagrant-vmware-desktop/driver/base.rb
spec/vagrant-vmware-desktop/driver_spec.rb

Determine the correct product type based on product name and the license
in use. Include the product type when executing the `vmrun` commands.
Fixes #31 #32

Include product type within `vmrun` commands

---

lib/vagrant-vmware-desktop/driver/base.rb

The `e1000` driver has started to be dropped on more recent systems
causing issues using this as the default device. The `e1000e` driver is
widely available and works well as a default replacement.
Fixes #50 #54

Update the default NIC device

---

lib/vagrant-vmware-desktop/driver/base.rb
spec/vagrant-vmware-desktop/driver_spec.rb

When creating a linked clone, manually create a snapshot with a unique
name to link the clone. This prevents the generic "Clone" name from
being used. We use the basename of the destination directory as it will
be a unique UUID. The name of the snapshot and the source of the vmx
file the link clone originated are stored in vm directory.
When deleting the guest, the vm directory is checked for files
containing the original vmx path and the snapshot name. If they exist,
the snapshot will be deleted before the vm directory contents are
destroyed.
Fixes #38 #43

Update linked clone behavior

---

.ci/.ci-utility-files/common.sh
.ci/build-macos-dmg
.ci/create-cache
.ci/notarize-file
.ci/restore-cache
.ci/utility-binaries-prerelease
.ci/utility-bins-information
.ci/utility-information
.github/workflows/build-utility-packages.yml
.github/workflows/utility-binaries-build.yml
.github/workflows/utility-prerelease.yml
.github/workflows/utility-release.yml

This enables macOS package builds using the same strategy 
applied to Vagrant packages. Includes some helper script
updates copied over from vagrant-installers and updates
to the utility dev/nightly builds.

Enable builds for macOS packages

---

lib/vagrant-vmware-desktop/driver/base.rb
spec/vagrant-vmware-desktop/driver_spec.rb

When detecting product type, Fusion does not use player for standard
licenses. Remove license type check when running under Fusion and set
the type only based on the Fusion product.
Fixes #78

Only single product type for Fusion

---

.github/workflows/prune.yml

Enables pruning releases from both the public repository
and the private build repository. Impact on the public
repository will be the retention of the last 10 nightly
builds.

Enable pruning globally

---

.ci/build-macos-dmg
.ci/utility-macos-rename-release
.github/workflows/utility-release.yml

Use a `_universal` suffix when building the macOS package. During
the release process, generate valid macOS file names supported by
the release system.

Update macOS package naming

---

lib/vagrant-vmware-desktop/driver/base.rb
spec/vagrant-vmware-desktop/driver_spec.rb

The actual command arguments should be mapped to string values. However,
the final argument used in the splat to the `Subprocess#execute` method
will be the options for the execution, which should remain as a `Hash`.
Perform the type casting prior to pushing the options.
Fixes #86

Fix vmexec command formatting

---

lib/vagrant-vmware-desktop/guest_cap/linux/mount_vmware_shared_folder.rb

This is both a bug report and fix since it was easy enough. The bug happens when trying to run vagrant up using this plugin AND you are mounting folders AND the mount_options is an empty array. The following error gets dumped when the mounting section happens during vagrant up:
My vagrant file by default passes an empty array for mount_options unless something more specific gets specified.
The error seems to be that an extra comma gets appended to the option string passed after `-o`. This trailing comma should not be appended unless there are actual mount_options because it will cause this error. To fix, I just added a quick array length check.
I also noticed this might be a potential issue on line 83 but don't know enough about this codebase or the kernel module.

Mount Folders Unknown Options Fix

---

lib/vagrant-vmware-desktop/action.rb
lib/vagrant-vmware-desktop/cap/disk.rb
lib/vagrant-vmware-desktop/driver/base.rb
lib/vagrant-vmware-desktop/plugin.rb
locales/en.yml
spec/vagrant-vmware-desktop/cap/disk_spec.rb
spec/vagrant-vmware-desktop/driver_spec.rb

Fixes the primary disk resizing to handle types other than scsi. If the guest is a linked clone, the resizing of the disk will be ignored and a warning will be emitted (linked disks cannot be resized).
This also removes the experimental guards from the disks feature.
Fixes hashicorp/vagrant#13290
Fixes hashicorp/vagrant#13230

Fix primary disk resize

---

go_src/vagrant-vmware-utility/driver/advanced.go
go_src/vagrant-vmware-utility/driver/simple.go
go_src/vagrant-vmware-utility/utility/dhcp_lease_file.go
go_src/vagrant-vmware-utility/utility/dhcp_lease_file_test.go
go_src/vagrant-vmware-utility/utility/networking_file_test.go
go_src/vagrant-vmware-utility/utility/utility_test.go

When multiple valid lease entries exist within the lease file for a given MAC address, flag the MAC address and reject any matching entries from being allowed within the lookup list.
Fixes #36

Fix multi entry lease handling

---

lib/vagrant-vmware-desktop/driver/base.rb

This updates the read_ip helper to use the guest tools first when
attempting to lookup a guest address, and falling back to using
the DHCP lease address when it is unavailable.
Fixes #114

Fix read_ip lookup ordering to use guest tools first

---

lib/vagrant-vmware-desktop/driver/base.rb
spec/vagrant-vmware-desktop/driver_spec.rb

Adds the `-wait` flag when getting the address via guest tools. Can be useful for resolving stuck waits as [described by @eszense](https://github.com/hashicorp/vagrant-vmware-desktop/issues/93#issuecomment-2068043594).

Add wait flag for address lookup

---

go_src/vagrant-vmware-utility/driver/core.go

Remove the vl check when checking license version due to many reports
of bad matching based on available capabilities.

Remove "vl" checking from license

---

lib/vagrant-vmware-desktop/driver/base.rb
lib/vagrant-vmware-desktop/errors.rb
locales/en.yml

If a process exits with an error and the output indicates the
operation was canceled, attempt to inspect the vmware log file
to determine the error causing the cancelation. If error information
cannot be extracted, fallback to default behavior.

Provide a best effort inspection for cancel errors

---

lib/vagrant-vmware-desktop/driver/base.rb
spec/vagrant-vmware-desktop/driver_spec.rb

When using guest tools to read the IP, include retry on the command
and rescue out the timeout error to allow MAC address lookup to
be performed as well.

Retry on failed attempt to get guest IP

---

lib/vagrant-vmware-desktop/action.rb

While migrating from Virtualbox to VMWare, I noticed a difference in Vagrant's behavior.
When using Virtualbox and running 'vagrant up' with the VMs already running, Vagrant still executes the "run: 'always" provisioners. However, all the provisioners are skipped when doing the same thing with VMWare.
After some investigation, I noticed that the Virtualbox behavior was added in 2016 in this commit:
https://github.com/hashicorp/vagrant/commit/e42f346b1d5891b5bd3651564894b95ed3b8b6cc
Issue link: https://github.com/hashicorp/vagrant/issues/4421
The commit added this behavior for the Virtualbox/Hyper-V/Docker providers. However, it appears that the fix was never ported to the VMWare plugin which results in inconsistent behavior.
I validated that with this change, 'vagrant up' runs the …

vagrant up should execute provisioners with 'run' set to 'always' when the VM is running like with Virtualbox/Hyper-V/Docker

---

lib/vagrant-vmware-desktop.rb
lib/vagrant-vmware-desktop/cap.rb
lib/vagrant-vmware-desktop/cap/disk.rb
lib/vagrant-vmware-desktop/driver.rb
lib/vagrant-vmware-desktop/errors.rb
lib/vagrant-vmware-desktop/guest_cap.rb
lib/vagrant-vmware-desktop/guest_cap/linux.rb
locales/en.yml
spec/spec_base.rb
spec/vagrant-vmware-desktop/cap/disk_spec.rb

This extends #134 PR to add test coverage, force error when primary is not properly located, and includes some loading cleanup.

Primary disk checks and cleanup

---

lib/vagrant-vmware-desktop/driver/base.rb

This PR fixes this issue: https://github.com/hashicorp/vagrant-vmware-desktop/issues/149
When executing a vagrant snapshot restore with VMWare, there is a timeout of 45 seconds to start the VM.
VMWare restores the snapshot while starting the VM which can easily take more than 45 seconds.
This results in the following error:
```
Vagrant timed out while trying to start the VMware machine. This
error is caused by VMware never successfully starting the machine.
This can often be fixed by simply retrying. If the error persists,
please verify that VMware is functional. This is not a Vagrant
issue.
```
There is no such timeout in the Vagrant's Virtualbox plugin. Since the comment in the code mentions that this timeout was included since vmrun can hang, I chose to keep it, but to increase it …

vagrant snapshot restore times out due to hard coded 45 seconds timeout

---

lib/vagrant-vmware-desktop/cap/disk.rb

Adding a SCSI disk without specifying an adapter_type currently gives error in VMware Fusion
```
The device type "buslogic" specified for "scsi0" is not supported by VMware Fusion 13.6.2.
``` 
However, setting an adapter_type "pvscsi" gives an malformed warning 
`WARN disk: `**_lsilogic_**` is not valid. Should be one of ide, buslogic, lsilogic! Setting adapter type to lsilogic`
This PR adds pvscsi as an accepted adapter_type and fix the warning message.
N.B.:
pvscsi is a supported adapter_type in VMware Fusion and is the default when adding an SCSI disk on the GUI
https://knowledge.broadcom.com/external/article/313507/configuring-disks-to-use-vmware-paravirt.html

Support pvscsi disk adapter type

---

go_src/vagrant-vmware-utility/driver/core.go

Reports of the new free licenses show the license check produces
empty content. If empty content is encountered, just default to
marking the installation as professional.
Fixes #102
Fixes #91

Default to professional license when license data is empty

---

go_src/vagrant-vmware-utility/utility/dhcp_lease_file.go
go_src/vagrant-vmware-utility/utility/dhcp_lease_file_test.go
lib/vagrant-vmware-desktop/action.rb
lib/vagrant-vmware-desktop/action/base_mac_config_warning.rb
locales/en.yml

When multiple lease entries are encountered for a MAC address, use the most recently generated entry _if_ the entry hostname's match. If the hostnames of the entries do not match, the MAC address is marked as invalid and none will be used.
Because this problem generally originates when the `base_mac` value is set within a Vagrantfile provided inside the box, a check is added during the guest creation for the `base_mac` being set. If it is detected, a warning is generated with information of the problem it may cause, and how it can be fixed locally. 
Fixes: #129

Update multiple lease entry handling
